/**
 * backfill.ts
 *
 * Generates puzzles for one or all games and writes them to Firestore.
 *
 * Usage (from the functions/ directory):
 *
 *   npx ts-node backfill.ts --game=takes --count=30
 *   npx ts-node backfill.ts --all --count=10        ← parallel worker threads
 *   npx ts-node backfill.ts --game=mate-in-2 --count=60 --dry-run
 *
 * --all spawns one worker thread per game so all 12 run in parallel.
 * The algorithm is identical to the single-game path — no shortcuts.
 *
 * Available games:
 *   takes, solitaire, check, smothered, chess-solitaire,
 *   queen-vs-pawn, king-and-pawn, rook-endgame, zugzwang,
 *   mate-in-1, mate-in-2, mate-in-3
 */

import { isMainThread, parentPort, workerData, Worker } from "worker_threads";
import * as path from "path";
import * as fs from "fs";

// Load .env.local before any other imports so credentials are available.
const envPath = path.resolve(__dirname, "../.env.local");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const eq = line.indexOf("=");
    if (eq < 1 || line.startsWith("#")) continue;
    const key = line.slice(0, eq).trim();
    if (!process.env[key]) process.env[key] = line.slice(eq + 1).trim();
  }
}

// ─── Worker entry point ───────────────────────────────────────────────────────
// When this file is loaded as a worker thread, workerData contains { game, count, dryRun }.
// The worker runs the full generation pipeline and posts log lines back to the main thread.

if (!isMainThread) {
  runWorker().catch((err) => {
    parentPort?.postMessage({ type: "error", text: String(err) });
    process.exit(1);
  });
}

async function runWorker() {
  const { game, count, dryRun } = workerData as { game: string; count: number; dryRun: boolean };

  // Each worker needs its own Firebase admin instance.
  const admin = await import("firebase-admin");
  const { Timestamp } = await import("firebase-admin/firestore");

  const generate = await import("./generate");
  const { isGameId, randomDifficulty, generatePuzzle, puzzleSignature, serializeForFirestore } = generate;
  type GameId = import("./generate").GameId;

  function log(text: string) {
    parentPort?.postMessage({ type: "log", game, text });
  }

  if (!isGameId(game)) {
    log(`Unknown game: ${game}`);
    return;
  }

  function getCredential() {
    if (process.env.FIREBASE_SERVICE_ACCOUNT_KEY) {
      return admin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_KEY));
    }
    const keyPath =
      process.env.GOOGLE_APPLICATION_CREDENTIALS ||
      path.resolve(__dirname, "./serviceAccountKey.json");
    return admin.credential.cert(keyPath as string);
  }

  // Each worker gets a unique app name to avoid "already initialized" errors.
  const appName = `worker-${game}`;
  const app = admin.initializeApp({ credential: getCredential() }, appName);
  const db = admin.firestore(app);

  const col = db.collection("games").doc(game).collection("puzzles");

  function generateUnique(gid: GameId, seen: Set<string>) {
    for (let attempt = 0; attempt < 50; attempt++) {
      const result = generatePuzzle(gid, randomDifficulty());
      const sig = puzzleSignature(gid, result.data);
      if (!seen.has(sig)) { seen.add(sig); return result; }
    }
    return generatePuzzle(gid, randomDifficulty());
  }

  // Find the current max sequential ID so new puzzles continue from there.
  const maxSnap = await col.orderBy("id", "desc").limit(1).get();
  const maxId = maxSnap.empty ? 0 : (maxSnap.docs[0].data().id as number ?? 0);

  let created = 0;
  let skipped = 0;
  let failed = 0;
  const seen = new Set<string>();

  for (let i = 0; i < count; i++) {
    const id = maxId + i + 1;
    const docRef = col.doc(String(id));

    if (!dryRun) {
      const existing = await docRef.get();
      if (existing.exists) {
        log(`  ⏭  #${id} — already exists`);
        skipped++;
        continue;
      }
    }

    try {
      const { difficulty, data } = generateUnique(game as GameId, seen);

      if (!dryRun) {
        await docRef.set({
          id,
          difficulty,
          gameType: game,
          ...serializeForFirestore(data),
          releaseDate: Timestamp.fromMillis(Date.now()),
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          status: "scheduled",
          autoGenerated: true,
        });
      }

      log(`  ✅ #${id} — ${difficulty}${dryRun ? " [dry]" : ""}`);
      created++;
    } catch (err) {
      log(`  ❌ #${id} — ${err}`);
      failed++;
    }
  }

  parentPort?.postMessage({ type: "done", game, created, skipped, failed });
}

// ─── Main thread ──────────────────────────────────────────────────────────────

if (isMainThread) {
  main().catch((err) => {
    console.error("\nFatal:", err);
    process.exit(1);
  });
}

function parseArgs() {
  const args = process.argv.slice(2);
  const get = (flag: string) =>
    args.find((a) => a.startsWith(`--${flag}=`))?.split("=")[1];
  return {
    game: get("game") ?? "",
    count: parseInt(get("count") ?? "30", 10),
    dryRun: args.includes("--dry-run"),
    all: args.includes("--all"),
  };
}

async function main() {
  const { game, count, dryRun, all } = parseArgs();

  if (all) {
    await runAllParallel(count, dryRun);
    return;
  }

  // Single-game path (original behaviour).
  const admin = await import("firebase-admin");
  const { Timestamp } = await import("firebase-admin/firestore");
  const generate2 = await import("./generate");
  const { GAME_IDS, isGameId, randomDifficulty, generatePuzzle, puzzleSignature, serializeForFirestore } = generate2;
  type GameId = import("./generate").GameId;

  if (!game || !isGameId(game)) {
    console.error(`\nError: --game must be one of:\n  ${GAME_IDS.join(", ")}\n`);
    console.error(`Or pass --all to generate all games in parallel.\n`);
    process.exit(1);
  }
  if (isNaN(count) || count < 1) {
    console.error("Error: --count must be a positive integer");
    process.exit(1);
  }

  function getCredential() {
    if (process.env.FIREBASE_SERVICE_ACCOUNT_KEY) {
      return admin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_KEY));
    }
    const keyPath =
      process.env.GOOGLE_APPLICATION_CREDENTIALS ||
      path.resolve(__dirname, "./serviceAccountKey.json");
    return admin.credential.cert(keyPath as string);
  }

  admin.initializeApp({ credential: getCredential() });
  const db = admin.firestore();

  const col = db.collection("games").doc(game).collection("puzzles");

  console.log(`\nMinichess Backfill`);
  console.log(`  Game    : ${game}`);
  console.log(`  Count   : ${count}`);
  console.log(`  Dry run : ${dryRun}\n`);

  function generateUnique(gid: GameId, seen: Set<string>) {
    for (let attempt = 0; attempt < 50; attempt++) {
      const result = generatePuzzle(gid, randomDifficulty());
      const sig = puzzleSignature(gid, result.data);
      if (!seen.has(sig)) { seen.add(sig); return result; }
    }
    return generatePuzzle(gid, randomDifficulty());
  }

  // Find the current max sequential ID so new puzzles continue from there.
  const maxSnap = await col.orderBy("id", "desc").limit(1).get();
  const maxId = maxSnap.empty ? 0 : (maxSnap.docs[0].data().id as number ?? 0);
  console.log(`  Starting from ID : ${maxId + 1}\n`);

  let created = 0, skipped = 0, failed = 0;
  const seen = new Set<string>();

  for (let i = 0; i < count; i++) {
    const id = maxId + i + 1;
    const docRef = col.doc(String(id));

    if (!dryRun) {
      const existing = await docRef.get();
      if (existing.exists) {
        console.log(`  ⏭  #${id} — already exists, skipping`);
        skipped++;
        continue;
      }
    }

    try {
      const { difficulty, data } = generateUnique(game as GameId, seen);
      if (!dryRun) {
        await docRef.set({
          id, difficulty, gameType: game,
          ...serializeForFirestore(data),
          releaseDate: Timestamp.fromMillis(Date.now()),
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          status: "scheduled",
          autoGenerated: true,
        });
      }
      console.log(`  ✅ #${id} — ${difficulty}${dryRun ? " [dry]" : ""}`);
      created++;
    } catch (err) {
      console.error(`  ❌ #${id} — ${err}`);
      failed++;
    }
  }

  console.log(`\n${"─".repeat(50)}`);
  console.log(`Done — created: ${created} | skipped: ${skipped} | failed: ${failed}`);
}

// ─── Parallel runner ──────────────────────────────────────────────────────────

async function runAllParallel(count: number, dryRun: boolean) {
  const { GAME_IDS } = await import("./generate");

  console.log(`\nMinichess Parallel Backfill`);
  console.log(`  Games   : all ${GAME_IDS.length}`);
  console.log(`  Count   : ${count} per game`);
  console.log(`  Dry run : ${dryRun}`);
  console.log(`  Threads : ${GAME_IDS.length} (one per game)\n`);
  console.log(`${"─".repeat(50)}\n`);

  const totals: Record<string, { created: number; skipped: number; failed: number }> = {};

  await Promise.all(
    GAME_IDS.map(
      (game) =>
        new Promise<void>((resolve, reject) => {
          const worker = new Worker(__filename, {
            workerData: { game, count, dryRun },
            // ts-node registers TypeScript so the worker can import .ts files.
            execArgv: ["--require", "ts-node/register"],
          });

          worker.on("message", (msg: { type: string; game: string; text?: string; created?: number; skipped?: number; failed?: number }) => {
            if (msg.type === "log") {
              console.log(`[${msg.game.padEnd(15)}] ${msg.text}`);
            } else if (msg.type === "done") {
              totals[msg.game] = {
                created: msg.created ?? 0,
                skipped: msg.skipped ?? 0,
                failed: msg.failed ?? 0,
              };
            } else if (msg.type === "error") {
              console.error(`[${msg.game.padEnd(15)}] ERROR: ${msg.text}`);
            }
          });

          worker.on("error", reject);
          worker.on("exit", (code) => {
            if (code !== 0) reject(new Error(`Worker for ${game} exited with code ${code}`));
            else resolve();
          });
        })
    )
  );

  console.log(`\n${"─".repeat(50)}`);
  console.log(`\nSummary:\n`);
  let totalCreated = 0, totalSkipped = 0, totalFailed = 0;
  for (const game of GAME_IDS) {
    const t = totals[game] ?? { created: 0, skipped: 0, failed: 0 };
    console.log(`  ${game.padEnd(16)} created: ${t.created}  skipped: ${t.skipped}  failed: ${t.failed}`);
    totalCreated += t.created;
    totalSkipped += t.skipped;
    totalFailed += t.failed;
  }
  console.log(`\n  ${"TOTAL".padEnd(15)} created: ${totalCreated}  skipped: ${totalSkipped}  failed: ${totalFailed}`);
}
