import { onSchedule } from "firebase-functions/v2/scheduler";
import { onRequest } from "firebase-functions/v2/https";
import * as admin from "firebase-admin";
import { Timestamp } from "firebase-admin/firestore";
import { publishGamesBatch } from "./githubPublisher";
import {
  Difficulty,
  TAKES_BANK, SOLITAIRE_BANK, CHECK_BANK, SMOTHERED_BANK,
  CHESS_SOLITAIRE_BANK, QUEEN_VS_PAWN_BANK, KING_AND_PAWN_BANK,
  ROOK_ENDGAME_BANK, ZUGZWANG_BANK, MATE_IN_1_BANK, MATE_IN_2_BANK,
  MATE_IN_3_BANK, PuzzleBank,
} from "./puzzleBanks";

admin.initializeApp();
const db = admin.firestore();

const SECRETS = ["GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_BRANCH"];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Pick a random difficulty with equal 33% chance each. */
function randomDifficulty(): Difficulty {
  const roll = Math.random();
  if (roll < 1 / 3) return "easy";
  if (roll < 2 / 3) return "medium";
  return "hard";
}

/** Pick a random element from an array. */
function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Select one puzzle from a bank with the given difficulty.
 * Falls back to other difficulties in order (medium → easy → hard) if the
 * requested difficulty has no puzzles.
 */
function selectFromBank<T>(bank: PuzzleBank<T>, difficulty: Difficulty): { difficulty: Difficulty; data: T } {
  const fallback: Difficulty[] = difficulty === "easy"
    ? ["easy", "medium", "hard"]
    : difficulty === "medium"
    ? ["medium", "easy", "hard"]
    : ["hard", "medium", "easy"];

  for (const diff of fallback) {
    if (bank[diff].length > 0) {
      return { difficulty: diff, data: pick(bank[diff]) };
    }
  }
  throw new Error("Puzzle bank is empty for all difficulties");
}

/** Generate today's date as an integer YYYYMMDD in EST. */
function todayId(): number {
  const now = new Date();
  const estStr = now.toLocaleDateString("en-CA", { timeZone: "America/New_York" });
  return parseInt(estStr.replace(/-/g, ""), 10);
}

/** Convert a YYYYMMDD integer to a JS Date at midnight EST. */
function idToReleaseDate(id: number): Date {
  const s = String(id);
  const iso = `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}T05:00:00.000Z`; // midnight EST = 05:00 UTC
  return new Date(iso);
}

/** Write a generated puzzle to Firestore under games/{gameId}/puzzles/{id}. */
async function writePuzzleToFirestore(
  gameId: string,
  id: number,
  difficulty: Difficulty,
  puzzleData: object,
  releaseDate: Date,
): Promise<void> {
  await db
    .collection("games")
    .doc(gameId)
    .collection("puzzles")
    .doc(String(id))
    .set({
      id,
      difficulty,
      gameType: gameId,
      ...puzzleData,
      releaseDate: Timestamp.fromDate(releaseDate),
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      status: "scheduled",
      autoGenerated: true,
    });
}

// ─── Daily puzzle generator ───────────────────────────────────────────────────

const GAMES: Array<{ gameId: string; bank: PuzzleBank<object> }> = [
  { gameId: "takes", bank: TAKES_BANK as PuzzleBank<object> },
  { gameId: "solitaire", bank: SOLITAIRE_BANK as PuzzleBank<object> },
  { gameId: "check", bank: CHECK_BANK as PuzzleBank<object> },
  { gameId: "smothered", bank: SMOTHERED_BANK as PuzzleBank<object> },
  { gameId: "chess-solitaire", bank: CHESS_SOLITAIRE_BANK as PuzzleBank<object> },
  { gameId: "queen-vs-pawn", bank: QUEEN_VS_PAWN_BANK as PuzzleBank<object> },
  { gameId: "king-and-pawn", bank: KING_AND_PAWN_BANK as PuzzleBank<object> },
  { gameId: "rook-endgame", bank: ROOK_ENDGAME_BANK as PuzzleBank<object> },
  { gameId: "zugzwang", bank: ZUGZWANG_BANK as PuzzleBank<object> },
  { gameId: "mate-in-1", bank: MATE_IN_1_BANK as PuzzleBank<object> },
  { gameId: "mate-in-2", bank: MATE_IN_2_BANK as PuzzleBank<object> },
  { gameId: "mate-in-3", bank: MATE_IN_3_BANK as PuzzleBank<object> },
];

async function generateAllPuzzles(): Promise<{ path: string; content: object; gameId: string; id: number; difficulty: Difficulty; data: object }[]> {
  const id = todayId();
  const releaseDate = idToReleaseDate(id);
  const results = [];

  for (const { gameId, bank } of GAMES) {
    const difficulty = randomDifficulty();
    const { difficulty: actual, data } = selectFromBank(bank, difficulty);
    const content = { id, difficulty: actual, ...data };
    results.push({ path: `public/games/${gameId}.json`, content, gameId, id, difficulty: actual, data });
    console.log(`[generator] ${gameId}: ${actual}`);

    await writePuzzleToFirestore(gameId, id, actual, data, releaseDate);
    console.log(`[firestore] games/${gameId}/puzzles/${id} written`);
  }

  return results;
}

// ─── Scheduled function — midnight EST every day ──────────────────────────────

export const dailyPuzzleGenerator = onSchedule(
  {
    schedule: "0 0 * * *",
    timeZone: "America/New_York",
    secrets: SECRETS,
    memory: "256MiB",
    timeoutSeconds: 60,
  },
  async () => {
    console.log("[generator] Starting daily puzzle generation");
    const results = await generateAllPuzzles();
    const dateStr = String(todayId());
    const files = results.map(({ path, content }) => ({ path, content }));
    await publishGamesBatch(files, `chore: daily puzzles for ${dateStr}`);
    console.log(`[generator] Done — pushed ${files.length} puzzles for ${dateStr}`);
  }
);

// ─── HTTP trigger for manual runs / testing ──────────────────────────────────

export const generatePuzzlesNow = onRequest(
  { secrets: SECRETS, memory: "256MiB", timeoutSeconds: 60 },
  async (req, res) => {
    const secret = process.env.GENERATOR_SECRET ?? "";
    if (secret && req.headers["x-generator-secret"] !== secret) {
      res.status(401).json({ error: "unauthorized" });
      return;
    }

    try {
      console.log("[generator] Manual trigger");
      const results = await generateAllPuzzles();
      const dateStr = String(todayId());
      const files = results.map(({ path, content }) => ({ path, content }));
      await publishGamesBatch(files, `chore: manual puzzle generation for ${dateStr}`);
      res.json({ ok: true, date: dateStr, games: files.map((f) => f.path) });
    } catch (e) {
      console.error("[generator] Error:", e);
      res.status(500).json({ error: String(e) });
    }
  }
);
