import { onSchedule } from "firebase-functions/v2/scheduler";
import { onRequest } from "firebase-functions/v2/https";
import * as admin from "firebase-admin";
import { Timestamp } from "firebase-admin/firestore";
import { publishGamesBatch } from "./githubPublisher";
import {
  GAME_IDS, randomDifficulty, generatePuzzle, serializeForFirestore,
  type Difficulty,
} from "./generate";

admin.initializeApp();
const db = admin.firestore();

const SECRETS = ["GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_BRANCH"];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Generate today's date as an integer YYYYMMDD in EST. */
function todayId(): number {
  const now = new Date();
  const estStr = now.toLocaleDateString("en-CA", { timeZone: "America/New_York" });
  return parseInt(estStr.replace(/-/g, ""), 10);
}

/** Convert a YYYYMMDD integer to a JS Date at midnight EST. */
function idToReleaseDate(id: number): Date {
  const s = String(id);
  const iso = `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}T05:00:00.000Z`; // midnight EST = 05:00 UTC
  return new Date(iso);
}

/** Write a generated puzzle to Firestore under games/{gameId}/puzzles/{id}. */
async function writePuzzleToFirestore(
  gameId: string,
  id: number,
  difficulty: Difficulty,
  puzzleData: Record<string, unknown>,
  releaseDate: Date,
): Promise<void> {
  await db
    .collection("games")
    .doc(gameId)
    .collection("puzzles")
    .doc(String(id))
    .set({
      id,
      difficulty,
      gameType: gameId,
      ...serializeForFirestore(puzzleData),
      releaseDate: Timestamp.fromDate(releaseDate),
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      status: "scheduled",
      autoGenerated: true,
    });
}

// ─── Daily puzzle generator ───────────────────────────────────────────────────

async function generateAllPuzzles(): Promise<{ path: string; content: object }[]> {
  const id = todayId();
  const releaseDate = idToReleaseDate(id);
  const results: { path: string; content: object }[] = [];

  for (const gameId of GAME_IDS) {
    const { difficulty, data } = generatePuzzle(gameId, randomDifficulty());

    // GitHub JSON keeps the raw shape (real arrays); Firestore gets the
    // serialized shape (nested arrays as JSON strings).
    const content = { id, difficulty, ...data };
    results.push({ path: `public/games/${gameId}.json`, content });
    console.log(`[generator] ${gameId}: ${difficulty}`);

    await writePuzzleToFirestore(gameId, id, difficulty, data, releaseDate);
    console.log(`[firestore] games/${gameId}/puzzles/${id} written`);
  }

  return results;
}

// ─── Scheduled function — midnight EST every day ──────────────────────────────

export const dailyPuzzleGenerator = onSchedule(
  {
    schedule: "0 0 * * *",
    timeZone: "America/New_York",
    secrets: SECRETS,
    memory: "256MiB",
    timeoutSeconds: 120,
  },
  async () => {
    console.log("[generator] Starting daily puzzle generation");
    const results = await generateAllPuzzles();
    const dateStr = String(todayId());
    await publishGamesBatch(results, `chore: daily puzzles for ${dateStr}`);
    console.log(`[generator] Done — pushed ${results.length} puzzles for ${dateStr}`);
  }
);

// ─── HTTP trigger for manual runs / testing ──────────────────────────────────

export const generatePuzzlesNow = onRequest(
  { secrets: SECRETS, memory: "256MiB", timeoutSeconds: 120 },
  async (req, res) => {
    const secret = process.env.GENERATOR_SECRET ?? "";
    if (secret && req.headers["x-generator-secret"] !== secret) {
      res.status(401).json({ error: "unauthorized" });
      return;
    }

    try {
      console.log("[generator] Manual trigger");
      const results = await generateAllPuzzles();
      const dateStr = String(todayId());
      await publishGamesBatch(results, `chore: manual puzzle generation for ${dateStr}`);
      res.json({ ok: true, date: dateStr, games: results.map((f) => f.path) });
    } catch (e) {
      console.error("[generator] Error:", e);
      res.status(500).json({ error: String(e) });
    }
  }
);
