import { onSchedule } from "firebase-functions/v2/scheduler";
import { onRequest } from "firebase-functions/v2/https";
import * as admin from "firebase-admin";
import { Timestamp } from "firebase-admin/firestore";
import { publishGamesBatch } from "./githubPublisher";
import {
  GAME_IDS, randomDifficulty, generatePuzzle, serializeForFirestore,
  type Difficulty,
} from "./generate";

admin.initializeApp();
const db = admin.firestore();

const SECRETS = ["GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_BRANCH"];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Get the next sequential puzzle ID for a game (max existing + 1). */
async function nextId(gameId: string): Promise<number> {
  const snap = await db
    .collection("games")
    .doc(gameId)
    .collection("puzzles")
    .orderBy("id", "desc")
    .limit(1)
    .get();
  if (snap.empty) return 1;
  return ((snap.docs[0].data().id as number) ?? 0) + 1;
}

/** Write a generated puzzle to Firestore under games/{gameId}/puzzles/{id}. */
async function writePuzzleToFirestore(
  gameId: string,
  id: number,
  difficulty: Difficulty,
  puzzleData: Record<string, unknown>,
): Promise<void> {
  await db
    .collection("games")
    .doc(gameId)
    .collection("puzzles")
    .doc(String(id))
    .set({
      id,
      difficulty,
      gameType: gameId,
      ...serializeForFirestore(puzzleData),
      releaseDate: Timestamp.fromMillis(Date.now()),
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      status: "scheduled",
      autoGenerated: true,
    });
}

// ─── Daily puzzle generator ───────────────────────────────────────────────────

async function generateAllPuzzles(): Promise<{ path: string; content: object }[]> {
  const results: { path: string; content: object }[] = [];

  for (const gameId of GAME_IDS) {
    const id = await nextId(gameId);
    const { difficulty, data } = generatePuzzle(gameId, randomDifficulty());

    // GitHub JSON keeps the raw shape (real arrays); Firestore gets the
    // serialized shape (nested arrays as JSON strings).
    const content = { id, difficulty, ...data };
    results.push({ path: `public/games/${gameId}.json`, content });
    console.log(`[generator] ${gameId}: ${difficulty} → #${id}`);

    await writePuzzleToFirestore(gameId, id, difficulty, data);
    console.log(`[firestore] games/${gameId}/puzzles/${id} written`);
  }

  return results;
}

// ─── Scheduled function — midnight EST every day ──────────────────────────────

export const dailyPuzzleGenerator = onSchedule(
  {
    schedule: "0 0 * * *",
    timeZone: "America/New_York",
    secrets: SECRETS,
    memory: "256MiB",
    timeoutSeconds: 120,
  },
  async () => {
    console.log("[generator] Starting daily puzzle generation");
    const results = await generateAllPuzzles();
    await publishGamesBatch(results, `chore: daily puzzles`);
    console.log(`[generator] Done — pushed ${results.length} puzzles`);
  }
);

// ─── HTTP trigger for manual runs / testing ──────────────────────────────────

export const generatePuzzlesNow = onRequest(
  { secrets: SECRETS, memory: "256MiB", timeoutSeconds: 120 },
  async (req, res) => {
    const secret = process.env.GENERATOR_SECRET ?? "";
    if (secret && req.headers["x-generator-secret"] !== secret) {
      res.status(401).json({ error: "unauthorized" });
      return;
    }

    try {
      console.log("[generator] Manual trigger");
      const results = await generateAllPuzzles();
      await publishGamesBatch(results, `chore: manual puzzle generation`);
      res.json({ ok: true, games: results.map((f) => f.path) });
    } catch (e) {
      console.error("[generator] Error:", e);
      res.status(500).json({ error: String(e) });
    }
  }
);
