export const dynamic = "force-dynamic";

const VALID_GAMES = new Set([
  "takes", "solitaire", "check", "smothered", "chess-solitaire",
  "queen-vs-pawn", "king-and-pawn", "rook-endgame", "zugzwang",
  "mate-in-1", "mate-in-2", "mate-in-3", "survival",
]);

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ gameId: string; puzzleId: string }> }
) {
  try {
    const { gameId, puzzleId } = await params;

    if (!VALID_GAMES.has(gameId)) {
      return Response.json({ error: "unknown_game" }, { status: 404 });
    }

    const { getAdminDb } = await import("@/app/lib/firebase-admin");

    const snap = await getAdminDb()
      .collection("games")
      .doc(gameId)
      .collection("puzzles")
      .doc(puzzleId)
      .get();

    if (!snap.exists) {
      return Response.json({ error: "not_found" }, { status: 404 });
    }

    const data = snap.data()!;
    const { releaseDate, createdAt, status, autoGenerated, ...puzzle } = data;
    void releaseDate; void createdAt; void status; void autoGenerated;

    return Response.json(puzzle, {
      headers: { "Cache-Control": "public, s-maxage=86400" },
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`[puzzles/detail] error:`, e);
    return Response.json({ error: "internal", detail: msg }, { status: 500 });
  }
}
