import { getAdminDb } from "@/app/lib/firebase-admin";
import { GAME_FORMULAS } from "@/app/lib/scoring/formulas";
import type { GameId } from "@/app/lib/scoring/types";

export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ gameId: string; puzzleId: string }> }
) {
  const { gameId, puzzleId } = await params;

  if (!GAME_FORMULAS[gameId as GameId]) {
    return Response.json({ error: "unknown_game" }, { status: 404 });
  }

  try {
    const snap = await getAdminDb()
      .collection("games")
      .doc(gameId)
      .collection("puzzles")
      .doc(puzzleId)
      .get();

    if (!snap.exists) {
      return Response.json({ error: "not_found" }, { status: 404 });
    }

    const data = snap.data()!;
    // Strip server-only fields before sending to client
    const { releaseDate, createdAt, status, autoGenerated, ...puzzle } = data;
    void releaseDate; void createdAt; void status; void autoGenerated;

    return Response.json(puzzle, {
      headers: { "Cache-Control": "public, s-maxage=86400" },
    });
  } catch (e) {
    console.error(`[puzzles/${gameId}/${puzzleId}] error:`, e);
    return Response.json({ error: "internal" }, { status: 500 });
  }
}
