"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.generatePuzzlesNow = exports.dailyPuzzleGenerator = void 0;
const scheduler_1 = require("firebase-functions/v2/scheduler");
const https_1 = require("firebase-functions/v2/https");
const admin = __importStar(require("firebase-admin"));
const firestore_1 = require("firebase-admin/firestore");
const githubPublisher_1 = require("./githubPublisher");
const generate_1 = require("./generate");
admin.initializeApp();
const db = admin.firestore();
const SECRETS = ["GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_BRANCH"];
// ─── Helpers ──────────────────────────────────────────────────────────────────
/** Get the next sequential puzzle ID for a game (max existing + 1). */
async function nextId(gameId) {
    var _a;
    const snap = await db
        .collection("games")
        .doc(gameId)
        .collection("puzzles")
        .where("id", "<", 20000000)
        .orderBy("id", "desc")
        .limit(1)
        .get();
    if (snap.empty)
        return 1;
    return ((_a = snap.docs[0].data().id) !== null && _a !== void 0 ? _a : 0) + 1;
}
/** Write a generated puzzle to Firestore under games/{gameId}/puzzles/{id}. */
async function writePuzzleToFirestore(gameId, id, difficulty, puzzleData) {
    await db
        .collection("games")
        .doc(gameId)
        .collection("puzzles")
        .doc(String(id))
        .set(Object.assign(Object.assign({ id,
        difficulty, gameType: gameId }, (0, generate_1.serializeForFirestore)(puzzleData)), { releaseDate: firestore_1.Timestamp.fromMillis(Date.now()), createdAt: admin.firestore.FieldValue.serverTimestamp(), status: "scheduled", autoGenerated: true }));
}
// ─── Daily puzzle generator ───────────────────────────────────────────────────
async function generateAllPuzzles() {
    const results = [];
    for (const gameId of generate_1.GAME_IDS) {
        const id = await nextId(gameId);
        const { difficulty, data } = (0, generate_1.generatePuzzle)(gameId, (0, generate_1.randomDifficulty)());
        // GitHub JSON keeps the raw shape (real arrays); Firestore gets the
        // serialized shape (nested arrays as JSON strings).
        const content = Object.assign({ id, difficulty }, data);
        results.push({ path: `public/games/${gameId}.json`, content });
        console.log(`[generator] ${gameId}: ${difficulty} → #${id}`);
        await writePuzzleToFirestore(gameId, id, difficulty, data);
        console.log(`[firestore] games/${gameId}/puzzles/${id} written`);
    }
    return results;
}
// ─── Scheduled function — midnight EST every day ──────────────────────────────
exports.dailyPuzzleGenerator = (0, scheduler_1.onSchedule)({
    schedule: "0 0 * * *",
    timeZone: "America/New_York",
    secrets: SECRETS,
    memory: "256MiB",
    timeoutSeconds: 120,
}, async () => {
    console.log("[generator] Starting daily puzzle generation");
    const results = await generateAllPuzzles();
    await (0, githubPublisher_1.publishGamesBatch)(results, `chore: daily puzzles`);
    console.log(`[generator] Done — pushed ${results.length} puzzles`);
});
// ─── HTTP trigger for manual runs / testing ──────────────────────────────────
exports.generatePuzzlesNow = (0, https_1.onRequest)({ secrets: SECRETS, memory: "256MiB", timeoutSeconds: 120 }, async (req, res) => {
    var _a;
    const secret = (_a = process.env.GENERATOR_SECRET) !== null && _a !== void 0 ? _a : "";
    if (secret && req.headers["x-generator-secret"] !== secret) {
        res.status(401).json({ error: "unauthorized" });
        return;
    }
    try {
        console.log("[generator] Manual trigger");
        const results = await generateAllPuzzles();
        await (0, githubPublisher_1.publishGamesBatch)(results, `chore: manual puzzle generation`);
        res.json({ ok: true, games: results.map((f) => f.path) });
    }
    catch (e) {
        console.error("[generator] Error:", e);
        res.status(500).json({ error: String(e) });
    }
});
//# sourceMappingURL=index.js.map