"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.generatePuzzlesNow = exports.dailyPuzzleGenerator = void 0;
const scheduler_1 = require("firebase-functions/v2/scheduler");
const https_1 = require("firebase-functions/v2/https");
const admin = __importStar(require("firebase-admin"));
const firestore_1 = require("firebase-admin/firestore");
const githubPublisher_1 = require("./githubPublisher");
const puzzleBanks_1 = require("./puzzleBanks");
admin.initializeApp();
const db = admin.firestore();
const SECRETS = ["GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_BRANCH"];
// ─── Helpers ──────────────────────────────────────────────────────────────────
/** Pick a random difficulty with equal 33% chance each. */
function randomDifficulty() {
    const roll = Math.random();
    if (roll < 1 / 3)
        return "easy";
    if (roll < 2 / 3)
        return "medium";
    return "hard";
}
/** Pick a random element from an array. */
function pick(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}
/**
 * Select one puzzle from a bank with the given difficulty.
 * Falls back to other difficulties in order (medium → easy → hard) if the
 * requested difficulty has no puzzles.
 */
function selectFromBank(bank, difficulty) {
    const fallback = difficulty === "easy"
        ? ["easy", "medium", "hard"]
        : difficulty === "medium"
            ? ["medium", "easy", "hard"]
            : ["hard", "medium", "easy"];
    for (const diff of fallback) {
        if (bank[diff].length > 0) {
            return { difficulty: diff, data: pick(bank[diff]) };
        }
    }
    throw new Error("Puzzle bank is empty for all difficulties");
}
/** Generate today's date as an integer YYYYMMDD in EST. */
function todayId() {
    const now = new Date();
    const estStr = now.toLocaleDateString("en-CA", { timeZone: "America/New_York" });
    return parseInt(estStr.replace(/-/g, ""), 10);
}
/** Convert a YYYYMMDD integer to a JS Date at midnight EST. */
function idToReleaseDate(id) {
    const s = String(id);
    const iso = `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}T05:00:00.000Z`; // midnight EST = 05:00 UTC
    return new Date(iso);
}
/** Write a generated puzzle to Firestore under games/{gameId}/puzzles/{id}. */
async function writePuzzleToFirestore(gameId, id, difficulty, puzzleData, releaseDate) {
    await db
        .collection("games")
        .doc(gameId)
        .collection("puzzles")
        .doc(String(id))
        .set(Object.assign(Object.assign({ id,
        difficulty, gameType: gameId }, puzzleData), { releaseDate: firestore_1.Timestamp.fromDate(releaseDate), createdAt: admin.firestore.FieldValue.serverTimestamp(), status: "scheduled", autoGenerated: true }));
}
// ─── Daily puzzle generator ───────────────────────────────────────────────────
const GAMES = [
    { gameId: "takes", bank: puzzleBanks_1.TAKES_BANK },
    { gameId: "solitaire", bank: puzzleBanks_1.SOLITAIRE_BANK },
    { gameId: "check", bank: puzzleBanks_1.CHECK_BANK },
    { gameId: "smothered", bank: puzzleBanks_1.SMOTHERED_BANK },
    { gameId: "chess-solitaire", bank: puzzleBanks_1.CHESS_SOLITAIRE_BANK },
    { gameId: "queen-vs-pawn", bank: puzzleBanks_1.QUEEN_VS_PAWN_BANK },
    { gameId: "king-and-pawn", bank: puzzleBanks_1.KING_AND_PAWN_BANK },
    { gameId: "rook-endgame", bank: puzzleBanks_1.ROOK_ENDGAME_BANK },
    { gameId: "zugzwang", bank: puzzleBanks_1.ZUGZWANG_BANK },
    { gameId: "mate-in-1", bank: puzzleBanks_1.MATE_IN_1_BANK },
    { gameId: "mate-in-2", bank: puzzleBanks_1.MATE_IN_2_BANK },
    { gameId: "mate-in-3", bank: puzzleBanks_1.MATE_IN_3_BANK },
];
async function generateAllPuzzles() {
    const id = todayId();
    const releaseDate = idToReleaseDate(id);
    const results = [];
    for (const { gameId, bank } of GAMES) {
        const difficulty = randomDifficulty();
        const { difficulty: actual, data } = selectFromBank(bank, difficulty);
        const content = Object.assign({ id, difficulty: actual }, data);
        results.push({ path: `public/games/${gameId}.json`, content, gameId, id, difficulty: actual, data });
        console.log(`[generator] ${gameId}: ${actual}`);
        await writePuzzleToFirestore(gameId, id, actual, data, releaseDate);
        console.log(`[firestore] games/${gameId}/puzzles/${id} written`);
    }
    return results;
}
// ─── Scheduled function — midnight EST every day ──────────────────────────────
exports.dailyPuzzleGenerator = (0, scheduler_1.onSchedule)({
    schedule: "0 0 * * *",
    timeZone: "America/New_York",
    secrets: SECRETS,
    memory: "256MiB",
    timeoutSeconds: 60,
}, async () => {
    console.log("[generator] Starting daily puzzle generation");
    const results = await generateAllPuzzles();
    const dateStr = String(todayId());
    const files = results.map(({ path, content }) => ({ path, content }));
    await (0, githubPublisher_1.publishGamesBatch)(files, `chore: daily puzzles for ${dateStr}`);
    console.log(`[generator] Done — pushed ${files.length} puzzles for ${dateStr}`);
});
// ─── HTTP trigger for manual runs / testing ──────────────────────────────────
exports.generatePuzzlesNow = (0, https_1.onRequest)({ secrets: SECRETS, memory: "256MiB", timeoutSeconds: 60 }, async (req, res) => {
    var _a;
    const secret = (_a = process.env.GENERATOR_SECRET) !== null && _a !== void 0 ? _a : "";
    if (secret && req.headers["x-generator-secret"] !== secret) {
        res.status(401).json({ error: "unauthorized" });
        return;
    }
    try {
        console.log("[generator] Manual trigger");
        const results = await generateAllPuzzles();
        const dateStr = String(todayId());
        const files = results.map(({ path, content }) => ({ path, content }));
        await (0, githubPublisher_1.publishGamesBatch)(files, `chore: manual puzzle generation for ${dateStr}`);
        res.json({ ok: true, date: dateStr, games: files.map((f) => f.path) });
    }
    catch (e) {
        console.error("[generator] Error:", e);
        res.status(500).json({ error: String(e) });
    }
});
//# sourceMappingURL=index.js.map